export const AppPermissions = {
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  LEAD_VIEW: 'LEAD_VIEW',
  LEAD_CREATE: 'LEAD_CREATE',
  LEAD_UPDATE: 'LEAD_UPDATE',
  LEAD_DELETE: 'LEAD_DELETE',

  DASHBOARD_ADMIN_VIEW: 'DASHBOARD_ADMIN_VIEW',
  DASHBOARD_TEAM_VIEW: 'DASHBOARD_TEAM_VIEW',
  DASHBOARD_AGENT_VIEW: 'DASHBOARD_AGENT_VIEW',

  AI_ANALYTICS_VIEW: 'AI_ANALYTICS_VIEW',
  AI_PIPELINE_RUN: 'AI_PIPELINE_RUN',

  FRAUD_VIEW: 'FRAUD_VIEW',
  FRAUD_REVIEW: 'FRAUD_REVIEW',

  RECOMMENDATION_VIEW: 'RECOMMENDATION_VIEW',
  ML_EXPERIMENT_VIEW: 'ML_EXPERIMENT_VIEW'
} as const;

export type AppPermission =
  typeof AppPermissions[keyof typeof AppPermissions];
